name: React App CI/CD

on:
  push:
    branches:
      - main # trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main # trigger on pull requests targeting the main branch

jobs:
  build: # continuous integration
    runs-on: ubuntu-latest # this specifices the OS for the build environment

    steps:
      - name: Checkout code # step 1: checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js # step 2: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or desired Node.js version

      - name: Install dependencies # step 3: install dependencies
        run: npm install

      - name: Run tests # step 4: run tests
        run: npm test -- --watchAll=false # adjust this if you have specific test commands

      - name: Build React app # step 5: build react app
        run: npm run build
