name: React App CI/CD

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VITE_APP_FIREBASE_API_KEY: ${{ secrets.VITE_APP_FIREBASE_API_KEY }}
  VITE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_APP_FIREBASE_AUTH_DOMAIN }}
  VITE_APP_FIREBASE_PROJECT_ID: ${{ secrets.VITE_APP_FIREBASE_PROJECT_ID }}
  VITE_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_APP_FIREBASE_STORAGE_BUCKET }}
  VITE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_APP_FIREBASE_MESSAGING_SENDER_ID }}
  VITE_APP_FIREBASE_APP_ID: ${{ secrets.VITE_APP_FIREBASE_APP_ID }}

on:
  push:
    branches:
      - master # trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - master # trigger on pull requests targeting the main branch

jobs:
  build: # continuous integration
    runs-on: ubuntu-latest # this specifices the OS for the build environment

    steps:
      - name: Checkout code # step 1: checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js # step 2: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or desired Node.js version

      - name: Install dependencies # step 3: install dependencies
        run: npm install

      - name: Run tests # step 4: run tests
        run: npm test -- --watchAll=false # adjust this if you have specific test commands

      - name: Build React app # step 5: build react app
        run: npm run build
  
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}